url: http://www.fulbournwindmill.org.uk
name: Fulbourn Windmill
description: >
  All about the windmill in Fulbourn,
  Cambridgeshire, UK

baseurl: "" # the subpath of your site, e.g. /blog
facebook_name: fulbournwindmill
email: fulbourn.windmill.cio@gmail.com
google_analytics_id: UA-45611487-1

# Build settings
markdown: kramdown

collections:
  - events
