url: http://www.fulbournwindmill.org.uk
name: Fulbourn Windmill
description: >
  All about the windmill in Fulbourn,
  Cambridgeshire, UK

baseurl: "" # the subpath of your site, e.g. /blog
twitter_name: fulbournmill
instagram_name: fulbournwindmill
facebook_name: fulbournwindmill
email: fulbournwindmill@gmail.com

# Build settings
markdown: kramdown

collections:
- events
